version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/repo3/3-pilot.sazag.in
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: afterinstallhook.sh
      timeout: 1000
      runas: ubuntu
